### ISSUE TITLE
Moving Away From Replit

### ISSUE THREAD

**Issue by dacoder101** [lumauser/Mike-Ehrmantraut-Bot#2]
With Replit's recent changes, hosting a bot on Replit (like what is being done currently) is unideal. There are multiple other service hosting options, but I also have a Raspberry Pi which can be always on, free of charge. *I would need to create a new Discord application with the same bot and kick the old one, or simply give me your API key, but it's a better solution than Replit.*

**Comment by dacoder101** [comment]
Also, you should be able to remove `webserver.py` from the repository after navigating to a different hosting option.

**Comment by lumauser** [comment]
Aight thanks.
